<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
	<RootNamespace>WeGUI</RootNamespace>
	<AssemblyName>WeGUI</AssemblyName>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<None Include="Shaders/**" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="OpenTK" Version="4.9.4" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Shaders\shaderRect.frag">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Shaders\shaderRect.vert">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>


</Project>
